### ISSUE TITLE
Get Cross Sections libraries的问题

### ISSUE THREAD

**Issue by AlliTTson** [t2015q/OpenMC-Users-Guide#1]
@t2015q 您好！首先非常感谢你的教程，真的很有用。
我在安装截面数据库的时候，使用了您的方法（官网上并没有您这么详细的步骤，感谢子），下载了第一个提到的数据库（可以看到第一个附件图片，修改了bashrc文件路径），但是出问题的是打开openmc时显示cross_sections.xml缺少O18的核素信息
(报错ERROR: Could not find nuclide O18 in cross_sections.xml.)，我看了一下数据库内容确实少了O18（如图2）。
![issue1](https://user-images.githubusercontent.com/101382814/159187240-df443696-1d5e-41ee-9043-5620382581db.jpg)
![issue2](https://user-images.githubusercontent.com/101382814/159187248-7551eb4b-81b7-40b2-9b6e-b67e3af8735b.jpg)
请问您知道如何处理此类问题吗？还是可以采用什么方法跳过这一个报错？感谢！

**Comment by t2015q** [comment]
同学,你好!
     NNDC发的ENDF库好像没有O18这种核素，你也看到你的截面库列表清单“cross  sections .xml”也提示没有O18。
你换成O16吧,我当时代码就写O16,至于氧的其他核素我记不得ENDF库里面有没有。
另外，我19年毕业的，早已不接触核领域、转行了。这份教程估计还有点时效性，但没再维护了。后面的路你还是要自己填的，
我无能为力啊！
